services:
  tradesync:
    image: ghcr.io/exchanges-lab/tradesync:latest
    container_name: tradesync
    env_file:
      - .env
    networks:
      - cycle
    restart: unless-stopped

networks:
  cycle:
    external: true
